name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Show versions
        run: node -v && npm -v

      - name: Clean cache
        run: npm cache clean --force

      - name: Install deps (ci with fallback)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund || npm install --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Build
        run: npm run build
        env:
          CI: true
